# Generated by Django 4.2.5 on 2023-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('City Hall', 'City Hall'), ('Police Department', 'Police Department'), ('Department of Public Works', 'Department of Public Works'), ('Assessing Department', 'Assessing Department'), ('Building Department', 'Building Department')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
    ]
