# Generated by Django 4.2.5 on 2023-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_permitrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='permitrequest',
            name='username',
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='uploads/'),
        ),
    ]
