# Generated by Django 4.2.5 on 2023-11-12 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_remove_permitrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='status',
            field=models.CharField(default='IN PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='permitrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
