# Generated by Django 4.2.5 on 2023-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_permitrequest_status_permitrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitrequest',
            name='date_submitted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
